name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      year:
        description: 'Determines the year of the riddle.'
        required: true
        default: "auto"
      day:
        description: 'Determines the day of the riddle.'
        required: true
        default: "auto"
      part:
        description: 'Determines the part of the riddle.'
        required: true
        default: "auto"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      run: uv python install

    - name: Install the project
      run: uv sync

    - name: Run script
      env:
        AOC_SESSION: ${{ secrets.AOC_SESSION }}
      run: |
        uv run exec run --year "${{ inputs.year }}" --day "${{ inputs.day }}" --part "${{ inputs.part }}"
